Janus/Janus.Mask.Sqlite.WebApp/ViewModels/RemotePointViewModel.cs
using Janus.Communication.Remotes;
using System.ComponentModel.DataAnnotations;

namespace Janus.Mask.Sqlite.WebApp.ViewModels;

public sealed class RemotePointViewModel
{
    [Required]
    [Display(Name = "Node id")]
    public string NodeId { get; init; }
    [Required]
    [Display(Name = "Address")]
    public string Address { get; init; }
    [Required]
    [Display(Name = "Port")]
    public int Port { get; init; }
    public RemotePointTypes RemotePointType { get; init; }

    public override bool Equals(object? obj)
    {
        return obj is RemotePointViewModel model &&
               NodeId == model.NodeId &&
               Address == model.Address &&
               Port == model.Port &&
               RemotePointType == model.RemotePointType;
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(NodeId, Address, Port, RemotePointType);
    }

    public string String
        => $"({NodeId};{Address};{Port})";
}

Janus/Janus.Mask.Sqlite.WebApp/Controllers/RemotePointsController.cs
using Janus.Communication.Remotes;
using Janus.Mask.Sqlite.WebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using static Janus.Mask.Sqlite.WebApp.Commons.Helpers;

namespace Janus.Mask.Sqlite.WebApp.Controllers;
public class RemotePointsController : Controller
{
    private readonly SqliteMaskManager _maskManager;
    private Logging.ILogger<RemotePointsController>? _logger;

    public RemotePointsController(SqliteMaskManager maskManager, Logging.ILogger? logger = null)
    {
        _maskManager = maskManager;
        _logger = logger?.ResolveLogger<RemotePointsController>();
    }

    public async Task<IActionResult> Index()
    {
        var registeredRemotePoints = _maskManager.GetRegisteredRemotePoints()
                                           .Map(rp => new RemotePointViewModel()
                                           {
                                               Address = rp.Address,
                                               NodeId = rp.NodeId,
                                               Port = rp.Port,
                                               RemotePointType = rp.RemotePointType
                                           });

        var persistedRemotePoints = (await _maskManager.GetPersistedRemotePoints()
                                        .Map(result => result.Map(
                                            rp => new RemotePointViewModel()
                                            {
                                                Address = rp.Address,
                                                NodeId = rp.NodeId,
                                                Port = rp.Port,
                                                RemotePointType = rp.RemotePointType
                                            })))
                                        .Match(r => r, message => Enumerable.Empty<RemotePointViewModel>());

        var viewModel = new RemotePointsListViewModel()
        {
            RegisteredRemotePoints = registeredRemotePoints.ToList(),
            PersistedRemotePoints = persistedRemotePoints.ToList(),
            OperationOutcome = TempData.ToOperationOutcomeViewModel()
        };

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> RegisterRemotePoint([FromForm] string address, [FromForm] int port)
    {
        var undeterminedRemotePoint = new UndeterminedRemotePoint(address, port);
        var result = await _maskManager.RegisterRemotePoint(undeterminedRemotePoint);

        TempData["Constants.IsSuccess"] = result.IsSuccess;
        TempData["Constants.Message"] = result.Message;
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> PingRemotePoint([FromForm] string address, [FromForm] int port)
    {
        var undeterminedRemotePoint = new UndeterminedRemotePoint(address, port);
        var result = await _maskManager.SendHello(undeterminedRemotePoint);

        var operationOutcome = new OperationOutcomeViewModel()
        {
            IsSuccess = result.IsSuccess,
            Message = result.Message
        };

        TempData["Constants.IsSuccess"] = result.IsSuccess;
        TempData["Constants.Message"] = result.Message;
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> UnregisterRemotePoint([FromForm] string nodeId)
    {
        var remotePoint = _maskManager.GetRegisteredRemotePoints()
                                          .FirstOrDefault(x => x.NodeId == nodeId);
        // no such remote point found
        if (remotePoint is null)
        {
            TempData["Constants.IsSuccess"] = false;
            TempData["Constants.Message"] = $"No remote point with id {nodeId} registered.";
            return RedirectToAction(nameof(Index));
        }

        var result = await _maskManager.UnregisterRemotePoint(remotePoint);

        TempData["Constants.IsSuccess"] = result.IsSuccess;
        TempData["Constants.Message"] = result.Message;
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> PersistRemotePoint([FromForm] RemotePointViewModel viewModel)
    {

        RemotePoint remotePoint = viewModel switch
        {
            { RemotePointType: RemotePointTypes.MASK } => new MaskRemotePoint(viewModel.NodeId, viewModel.Address, viewModel.Port),
            { RemotePointType: RemotePointTypes.MEDIATOR } => new MediatorRemotePoint(viewModel.NodeId, viewModel.Address, viewModel.Port),
            { RemotePointType: RemotePointTypes.WRAPPER } => new WrapperRemotePoint(viewModel.NodeId, viewModel.Address, viewModel.Port),
            { RemotePointType: RemotePointTypes.UNDETERMINED } => new UndeterminedRemotePoint(viewModel.Address, viewModel.Port) // shouldn't reach this
        };
        var result = await _maskManager.PersistRemotePoint(remotePoint);

        TempData["Constants.IsSuccess"] = result.IsSuccess;
        TempData["Constants.Message"] = result.Message;
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> DeleteRemotePoint([FromForm] string nodeId)
    {
        var result = await _maskManager.DeleteRemotePoint(nodeId);

        TempData["Constants.IsSuccess"] = result.IsSuccess;
        TempData["Constants.Message"] = result.Message;
        return RedirectToAction(nameof(Index));
    }

}

Janus/Janus.Mask.Sqlite.WebApp/Views/RemotePoints/Index.cshtml
@model RemotePointsListViewModel

@{
    ViewData["Title"] = "Remote points";
}

<partial name="OperationOutcomePartial" model="Model.OperationOutcome" />

<div class="row">
    <form class="d-inline" method="post">
        <b class="me-1">Address:</b><input name="address" type="text" class="form-control d-inline-block w-25" />
        <b class="me-1">Port:</b><input name="port" type="number" class="form-control d-inline-block w-auto" />
        <input type="submit" value="Register" asp-action="RegisterRemotePoint" class="btn btn-primary" />
        <input type="submit" value="Send HELLO" asp-action="PingRemotePoint" class="btn btn-primary" />
    </form>
</div>
<hr />


<div class="row">
    <div class="col-6">
        <h3>Registered remote points</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameForInnerType((RemotePointViewModel model) => model.NodeId)
                    </th>
                    <th>
                        @Html.DisplayNameForInnerType((RemotePointViewModel model) => model.Address)
                    </th>
                    <th>
                        @Html.DisplayNameForInnerType((RemotePointViewModel model) => model.Port)
                    </th>
                    <th>
                        @Html.DisplayNameForInnerType((RemotePointViewModel model) => model.RemotePointType)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.RegisteredRemotePoints)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NodeId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Port)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RemotePointType)
                        </td>
                        <td>
                            <form method="post" asp-action="UnregisterRemotePoint" asp-controller="RemotePoints" class="d-inline">
                                <input type="hidden" name="nodeId" value="@item.NodeId" />
                                <input type="submit" class="btn btn-danger" value="Send BYE" />
                            </form>
                            <form method="post" asp-action="PersistRemotePoint" asp-controller="RemotePoints" class="d-inline">
                                <input type="hidden" name="NodeId" value="@item.NodeId" />
                                <input type="hidden" name="Address" value="@item.Address" />
                                <input type="hidden" name="Port" value="@item.Port" />
                                <input type="hidden" name="RemotePointType" value="@item.RemotePointType" />
                                <input type="submit" class="btn btn-outline-primary" value="Persist" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-6">
        <h3>Persisted remote points</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameForInnerType((RemotePointViewModel model) => model.NodeId)
                    </th>
                    <th>
                        @Html.DisplayNameForInnerType((RemotePointViewModel model) => model.Address)
                    </th>
                    <th>
                        @Html.DisplayNameForInnerType((RemotePointViewModel model) => model.Port)
                    </th>
                    <th>
                        @Html.DisplayNameForInnerType((RemotePointViewModel model) => model.RemotePointType)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PersistedRemotePoints)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NodeId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Port)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RemotePointType)
                        </td>
                        <td>
                            <form method="post" asp-action="RegisterRemotePoint" asp-controller="RemotePoints" class="d-inline">
                                <input type="hidden" name="NodeId" value="@item.NodeId" />
                                <input type="hidden" name="Address" value="@item.Address" />
                                <input type="hidden" name="Port" value="@item.Port" />
                                <input type="hidden" name="RemotePointType" value="@item.RemotePointType" />
                                <input type="submit" class="btn btn-primary" value="Register" />
                            </form>
                            <form method="post" asp-action="DeleteRemotePoint" asp-controller="RemotePoints" class="d-inline">
                                <input type="hidden" name="nodeId" value="@item.NodeId" />
                                <input type="submit" class="btn btn-danger" value="Delete" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>