Janus/Janus.Mask.Sqlite.WebApp/Controllers/CommandingController.cs
using Janus.Mask.Sqlite.WebApp.ViewModels;
using Janus.Serialization.Json;
using Microsoft.AspNetCore.Mvc;
using static Janus.Mask.Sqlite.WebApp.Commons.Helpers;

namespace Janus.Mask.Sqlite.WebApp.Controllers;
public class CommandingController : Controller
{
    private readonly SqliteMaskManager _maskManager;
    private readonly Logging.ILogger<CommandingController>? _logger;
    private readonly JsonSerializationProvider _jsonSerializationProvider;

    public CommandingController(SqliteMaskManager maskManager, JsonSerializationProvider jsonSerializationProvider, Logging.ILogger? logger)
    {
        _maskManager = maskManager;
        _jsonSerializationProvider = jsonSerializationProvider;
        _logger = logger?.ResolveLogger<CommandingController>();
    }

    public IActionResult Index()
    {

        var currentSchema = _maskManager.GetCurrentSchema()
                .Map(currentSchema => _jsonSerializationProvider.DataSourceSerializer.Serialize(currentSchema)
                                        .Match(
                                            r => r,
                                            r => "{}"
                                        ));

        var viewModel = new CommandingViewModel()
        {
            DataSourceJson = currentSchema ? PrettyJsonString(currentSchema.Value) : "No schema generated",
            OperationOutcome = TempData.ToOperationOutcomeViewModel()
        };


        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> RunCommand([FromForm] string commandText)
    {
        var commandResult =
            await _maskManager.CreateCommand(commandText)
                .Bind(command => _maskManager.RunCommand(command));


        TempData["Constants.IsSuccess"] = commandResult.IsSuccess;
        TempData["Constants.Message"] = commandResult.Message;
        return RedirectToAction(nameof(Index));
    }
}

Janus/Janus.Mask.Sqlite.WebApp/Controllers/QueryingController.cs
using Janus.Mask.Sqlite.WebApp.ViewModels;
using Janus.Serialization.Json;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using static Janus.Mask.Sqlite.WebApp.Commons.Helpers;

namespace Janus.Mask.Sqlite.WebApp.Controllers;
public class QueryingController : Controller
{
    private readonly SqliteMaskManager _maskManager;
    private readonly Logging.ILogger<QueryingController>? _logger;
    private readonly JsonSerializationProvider _jsonSerializationProvider;

    public QueryingController(SqliteMaskManager maskManager, JsonSerializationProvider jsonSerializationProvider, Logging.ILogger? logger)
    {
        _maskManager = maskManager;
        _jsonSerializationProvider = jsonSerializationProvider;
        _logger = logger?.ResolveLogger<QueryingController>();
    }

    public IActionResult Index()
    {
        var currentSchema = _maskManager.GetCurrentSchema()
                .Map(currentSchema => _jsonSerializationProvider.DataSourceSerializer.Serialize(currentSchema)
                                        .Match(
                                            r => r,
                                            r => "{}"
                                        ));

        var viewModel = new QueryingViewModel()
        {
            DataSourceJson = currentSchema ? PrettyJsonString(currentSchema.Value) : "No schema generated"
        };


        return View(viewModel);
    }

    [HttpPost]
    [Route("[controller]/")]
    public async Task<IActionResult> RunQuery([FromForm] string queryText)
    {
        var stopwatch = Stopwatch.StartNew();
        var queryResult =
            await _maskManager.CreateQuery(queryText)
                .Bind(query => _maskManager.RunQuery(query));
        var timeNeeded = stopwatch.ElapsedMilliseconds;
        stopwatch.Stop();

        var currentSchema = _maskManager.GetCurrentSchema()
                            .Map(currentSchema => _jsonSerializationProvider.DataSourceSerializer.Serialize(currentSchema)
                                                    .Match(
                                                        r => r,
                                                        r => "{}"
                                                    ));
        var tabularDataViewModel = new TabularDataViewModel()
        {
            ColumnDataTypes = queryResult
                                ? queryResult.Data.ColumnDataTypes.ToDictionary(_ => _.Key, _ => _.Value)
                                : new(),
            DataRows = queryResult
                        ? queryResult.Data.RowData.Map(row => row.ColumnValues.ToDictionary(cv => cv.Key, cv => cv.Value?.ToString() ?? "NULL")).ToList()
                        : new List<Dictionary<string, string>>(),
        };

        var viewModel = new QueryingViewModel()
        {
            DataSourceJson = currentSchema ? PrettyJsonString(currentSchema.Value) : "{}",
            QueryText = queryText,
            QueryResult = Option<TabularDataViewModel>.Some(tabularDataViewModel),
            OperationOutcome = Option<OperationOutcomeViewModel>.Some(
                            new OperationOutcomeViewModel()
                            {
                                IsSuccess = currentSchema && queryResult,
                                Message = currentSchema.Match(schema => "", () => "No schema generated.\n") +
                                          queryResult.Match(r => $"Query completed in {timeNeeded}ms", message => message)
                            })
        };

        return View(nameof(Index), viewModel);
    }

    public async Task<IActionResult> QueryRemotePoint()
    {
        var remotePoints =
            _maskManager.GetRegisteredRemotePoints()
            .Map(rp => new RemotePointViewModel
            {
                NodeId = rp.NodeId,
                Address = rp.Address,
                Port = rp.Port,
                RemotePointType = rp.RemotePointType
            });
        var viewModel = new QueryRemotePointViewModel
        {
            RemotePoints = remotePoints,
            SelectedRemotePoint = null,
            QueryText = string.Empty,
            OperationOutcome = Option<OperationOutcomeViewModel>.None,
            QueryResults = Option<TabularDataViewModel>.None
        };
        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> QueryRemotePoint([FromForm] string queryText, [FromForm] string nodeId)
    {
        var targetRemotePoint =
            _maskManager.GetRegisteredRemotePoints()
            .FirstOrDefault(rp => rp.NodeId.Equals(nodeId));

        var remotePoints =
            _maskManager.GetRegisteredRemotePoints()
            .Map(rp => new RemotePointViewModel
            {
                NodeId = rp.NodeId,
                Address = rp.Address,
                Port = rp.Port,
                RemotePointType = rp.RemotePointType
            });

        if (targetRemotePoint == null)
        {
            return View(new QueryRemotePointViewModel
            {
                RemotePoints = remotePoints,
                SelectedRemotePoint = remotePoints.FirstOrDefault(),
                QueryText = queryText,
                OperationOutcome = Option<OperationOutcomeViewModel>.Some(
                    new OperationOutcomeViewModel
                    {
                        IsSuccess = false,
                        Message = $"No remote point with id \"{nodeId}\""
                    })
            });
        }

        var stopwatch = Stopwatch.StartNew();
        var queryResult =
            await _maskManager.CreateQuery(queryText)
            .Bind(query => _maskManager.RunQueryOn(query, targetRemotePoint));
        var elapsedTime = stopwatch.Elapsed.Milliseconds;
        stopwatch.Stop();



        var viewModel = new QueryRemotePointViewModel
        {
            RemotePoints = remotePoints,
            SelectedRemotePoint = remotePoints.FirstOrDefault(rp => rp.NodeId.Equals(nodeId)),
            QueryText = queryText,
            OperationOutcome = Option<OperationOutcomeViewModel>.Some(
                new OperationOutcomeViewModel
                {
                    IsSuccess = queryResult.IsSuccess,
                    Message = $"{queryResult.Message}. Elapsed time: {elapsedTime}ms"
                }),
            QueryResults = queryResult.Match(
                r => Option<TabularDataViewModel>.Some(
                        new TabularDataViewModel
                        {
                            ColumnDataTypes = r.ColumnDataTypes.ToDictionary(_ => _.Key, _ => _.Value),
                            DataRows = r.RowData.Map(rd => rd.ColumnValues.ToDictionary(_ => _.Key, _ => _.Value?.ToString() ?? "NULL")).ToList()
                        }),
                msg => Option<TabularDataViewModel>.None
                )
        };

        return View(nameof(QueryRemotePoint), viewModel);
    }
}

Janus/Janus.Mask.Sqlite.WebApp/Controllers/SchemaController.cs
using Janus.Mask.Sqlite.WebApp.Commons;
using Janus.Mask.Sqlite.WebApp.ViewModels;
using Janus.Serialization.Json;
using Microsoft.AspNetCore.Mvc;
using static Janus.Mask.Sqlite.WebApp.Commons.Helpers;
using Results = Janus.Base.Resulting.Results;

namespace Janus.Mask.Sqlite.WebApp.Controllers;
public class SchemaController : Controller
{
    private readonly SqliteMaskManager _maskManager;
    private readonly JsonSerializationProvider _jsonSerializationProvider;

    public SchemaController(SqliteMaskManager maskManager, JsonSerializationProvider jsonSerializationProvider)
    {
        _maskManager = maskManager;
        _jsonSerializationProvider = jsonSerializationProvider;
    }

    public async Task<IActionResult> CurrentSchema()
    {
        var currentSchema = _maskManager.GetCurrentSchema();
        var schemaToJson =
            currentSchema.Match(
                                dataSource => _jsonSerializationProvider.DataSourceSerializer.Serialize(dataSource).Map(PrettyJsonString),
                                () => Results.OnFailure<string>("No schema generated")
                                );

        var viewModel = new DataSourceViewModel
        {
            DataSourceVersion = currentSchema.Match(ds => ds.Version, () => string.Empty),
            DataSourceJson = schemaToJson.Match(data => data, message => string.Empty),
            OperationOutcome =
                schemaToJson.IsSuccess
                ? Option<OperationOutcomeViewModel>.None
                : Option<OperationOutcomeViewModel>.Some(new OperationOutcomeViewModel
                {
                    IsSuccess = false,
                    Message = schemaToJson.Message
                })
        };

        return View(viewModel);
    }

    public async Task<IActionResult> SchemaLoading()
    {
        var currentSchema = _maskManager.GetCurrentSchema();
        var schemaToJson =
            currentSchema.Match(
                        dataSource => _jsonSerializationProvider.DataSourceSerializer.Serialize(dataSource).Map(PrettyJsonString),
                        () => Results.OnFailure<string>("No schema loaded")
                        );
        var viewModel = new SchemaLoadingViewModel
        {
            CurrentLoadedSchema = currentSchema.Map(_ => new DataSourceViewModel
            {
                DataSourceVersion = currentSchema.Match(ds => ds.Version, () => string.Empty),
                DataSourceJson = schemaToJson.Match(data => data, message => string.Empty)
            }),
            VisibleSchemas = new VisibleSchemasViewModel
            {
                RegisteredRemotePoints = _maskManager.GetRegisteredRemotePoints()
                                            .Map(rp => new RemotePointViewModel
                                            {
                                                NodeId = rp.NodeId,
                                                Address = rp.Address,
                                                Port = rp.Port,
                                                RemotePointType = rp.RemotePointType
                                            }).ToList()
            },
            OperationOutcome = Helpers.ToOperationOutcomeViewModel(TempData)
        };

        return View(viewModel);
    }

    public async Task<IActionResult> PersistedSchemas()
    {
        var persistedMediatedSchemas =
            (await _maskManager.GetAllPersistedSchemas())
                .Match(r => r, message => Enumerable.Empty<Persistence.Models.DataSourceInfo>())
                .Map(schema => new PersistedSchemaViewModel
                {
                    DataSourceVersion = schema.InferredDataSource.Version,
                    DataSourceJson = PrettyJsonString(_jsonSerializationProvider.DataSourceSerializer.Serialize(schema.InferredDataSource).Data ?? "{}"),
                    PersistedOn = schema.CreatedOn
                });

        var viewModel = new PersistedSchemaListViewModel
        {
            PersistedSchemas = persistedMediatedSchemas.ToList(),
            OperationOutcome = TempData.ToOperationOutcomeViewModel()
        };

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> PersistCurrentSchema()
    {
        if (_maskManager.GetCurrentSchema() && _maskManager.GetCurrentSchema())
        {
            var persistence =
                await _maskManager.PersistCurrentSchema(
                    _maskManager.GetCurrentSchema().Value
                    );

            TempData["Constants.IsSuccess"] = persistence.IsSuccess;
            TempData["Constants.Message"] = persistence.Message;
            return RedirectToAction(nameof(CurrentSchema));
        }
        else
        {
            TempData["Constants.IsSuccess"] = false;
            TempData["Constants.Message"] = "Can't persist a schema because no schema is generated";
            return RedirectToAction(nameof(CurrentSchema));
        }

    }

    [HttpPost]
    public async Task<IActionResult> LoadLatestSchemaFromPersistence()
    {
        var getCurrentSchema = await _maskManager.LoadLatestSchemaFromPersistence();
        var schemaToJson =
            getCurrentSchema.Bind(dataSource => _jsonSerializationProvider.DataSourceSerializer.Serialize(dataSource));

        TempData["Constants.IsSuccess"] = schemaToJson.IsSuccess;
        TempData["Constants.Message"] = schemaToJson.Message;
        return RedirectToAction(nameof(PersistedSchemas));
    }

    public async Task<IActionResult> DeleteSchemaFromPersistence([FromForm] string dataSourceVersion)
    {
        var deletion =
            await _maskManager.DeleteSchema(dataSourceVersion);

        TempData["Constants.IsSuccess"] = deletion.IsSuccess;
        TempData["Constants.Message"] = deletion.Message;
        return RedirectToAction(nameof(PersistedSchemas));
    }

    public async Task<IActionResult> VisibleSchemas()
    {
        var remotePoints = _maskManager.GetRegisteredRemotePoints();

        return View(new VisibleSchemasViewModel()
        {
            RegisteredRemotePoints = remotePoints.Map(rp => new RemotePointViewModel()
            {
                NodeId = rp.NodeId,
                Address = rp.Address,
                Port = rp.Port,
                RemotePointType = rp.RemotePointType
            }).ToList()
        });
    }

    [HttpGet]
    [Route("/GetSchema/{nodeId}")]
    public async Task<IActionResult> GetSchema(string nodeId)
    {
        var remotePoint = _maskManager.GetRegisteredRemotePoints()
                            .FirstOrDefault(rp => rp.NodeId.Equals(nodeId));

        if (remotePoint is null)
        {
            return NotFound();
        }

        var schemaResult =
            (await _maskManager.GetSchemaFrom(remotePoint))
                .Bind(_jsonSerializationProvider.DataSourceSerializer.Serialize);

        return schemaResult.Match(
            schema => (IActionResult)Content(schema, "application/json"),
            message => (IActionResult)StatusCode(500, message)
            );
    }

    [HttpGet]
    [Route("/LoadSchema/{nodeId}")]
    public async Task<IActionResult> LoadSchema(string nodeId)
    {
        var remotePoint =
            _maskManager.GetRegisteredRemotePoints()
            .FirstOrDefault(rp => rp.NodeId.Equals(nodeId));

        if (remotePoint is null)
        {
            return NotFound($"No remote point with {nodeId}");
        }

        var schemaLoading =
            (await _maskManager.LoadSchemaFrom(remotePoint))
            .Bind(_jsonSerializationProvider.DataSourceSerializer.Serialize);

        return schemaLoading.Match(
            schema => (IActionResult)Json(schema),
            message => (IActionResult)StatusCode(500, message)
            );
    }

    [HttpGet]
    [Route("/UnloadSchema/")]
    public async Task<IActionResult> UnloadSchema()
    {

        var schemaUnloading = _maskManager.UnloadSchema();

        return schemaUnloading.Match(
            message => (IActionResult)Json(message),
            message => (IActionResult)StatusCode(500, message)
            );
    }

}

Janus/Janus.Mask.Sqlite.WebApp/Views/Shared/OperationOutcomePartial.cshtml
@model Option<OperationOutcomeViewModel>

<div class="row">
    @if (Model)
    {
        @if (Model.Value.IsSuccess)
        {
            <span class="alert alert-success alert-dismissible">@Model.Value.Message</span>
        }
        else
        {
            <span class="alert alert-warning alert-dismissible">@Model.Value.Message</span>
        }
    }
</div>

Janus/Janus.Mask.Sqlite.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Janus Mask - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Janus.Mask.LiteDB.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Content/Images/janus_logo.png" style="max-height:72px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RemotePoints" asp-action="Index">Remote points</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link link-dark dropdown-toggle" id="navbarSchemaDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Schema management
                            </a>
                            <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarSchemaDropdown">
                                <li><a class="dropdown-item" asp-controller="Schema" asp-action="CurrentSchema">Current schema</a></li>
                                <li><a class="dropdown-item" asp-controller="Schema" asp-action="SchemaLoading">Schema loading</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link link-dark dropdown-toggle" id="navbarSchemaDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Querying
                            </a>
                            <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarSchemaDropdown">
                                <li><a class="dropdown-item" asp-controller="Querying" asp-action="Index">Querying on loaded schema</a></li>
                                <li><a class="dropdown-item" asp-controller="Querying" asp-action="QueryRemotePoint">Querying on a remote point</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link link-dark dropdown-toggle" id="navbarSchemaDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Commanding
                            </a>
                            <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarSchemaDropdown">
                                <li><a class="dropdown-item" asp-controller="Commanding" asp-action="Index">Commanding on loaded schema</a></li>
                                <li><a class="dropdown-item" asp-controller="Commanding" asp-action="CommandRemotePoint">Commanding on a remote point</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Janus Mask
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>